Run `repro.sh` to reproduce the crash. It works for me on x86-64 Arch Linux and PyPy 7.3.5.
